# Generated by Django 4.2.11 on 2026-01-17 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('CIVIL', 'Civil'), ('CORPORATE', 'Corporate'), ('FAMILY', 'Family'), ('CONSTITUTIONAL', 'Constitutional'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bar_council_id', models.CharField(max_length=100, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
