# Generated by Django 4.2.11 on 2026-02-09 03:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='advocate_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('official_id_card', models.FileField(blank=True, help_text='Upload Bar Council ID / Official Advocate ID', null=True, upload_to='advocate_ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('CRIMINAL', 'Criminal Law'), ('CIVIL', 'Civil Law'), ('CORPORATE', 'Corporate Law'), ('FAMILY', 'Family Law'), ('CONSTITUTIONAL', 'Constitutional Law'), ('CYBER', 'Cyber Law'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bar_council_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('languages_spoken', models.CharField(blank=True, help_text='Eg: English, Hindi, Telugu', max_length=255)),
                ('court_type', models.CharField(blank=True, help_text='District Court / High Court / Supreme Court', max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_advocates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advocate Profile',
                'verbose_name_plural': 'Advocate Profiles',
                'ordering': ['-is_verified', '-experience_years', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AssistantLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='advocates.advocateprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Lawyer',
                'verbose_name_plural': 'Assistant Lawyers',
                'ordering': ['-assigned_at'],
                'unique_together': {('advocate', 'user')},
            },
        ),
    ]
