# Generated by Django 4.2.11 on 2026-01-29 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('CRIMINAL', 'Criminal Law'), ('CIVIL', 'Civil Law'), ('CORPORATE', 'Corporate Law'), ('FAMILY', 'Family Law'), ('CONSTITUTIONAL', 'Constitutional Law'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Total years of legal experience')),
                ('bar_council_id', models.CharField(help_text='Official Bar Council Registration Number', max_length=100, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('verified', models.BooleanField(default=False, help_text='Verified by Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advocate Profile',
                'verbose_name_plural': 'Advocate Profiles',
                'ordering': ['-verified', '-experience_years', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AssistantLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='advocates.advocateprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Lawyer',
                'verbose_name_plural': 'Assistant Lawyers',
                'ordering': ['-assigned_at'],
                'unique_together': {('advocate', 'user')},
            },
        ),
    ]
