# Generated by Django 4.2.11 on 2026-02-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated languages (Eg: English, Hindi, Telugu)', max_length=255),
        ),
        migrations.AlterField(
            model_name='advocateprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='advocates/photos/'),
        ),
    ]
